import type { Drink } from './models';

const CATALOG_V4_TIMESTAMP = '2026-07-17T00:00:00.000Z';

// Спокойная семантическая палитра на основе Radix Colors. Цвета сгруппированы
// по типу напитка, поэтому большой каталог остаётся цельным, но легко сканируется.
const palette = {
  water: '#22B8CF',
  waterDeep: '#1098AD',
  teal: '#20A486',
  green: '#65A30D',
  lime: '#84B940',
  yellow: '#E6B422',
  amber: '#E99A2E',
  orange: '#ED7D31',
  coral: '#E6674F',
  red: '#D94A4A',
  ruby: '#C94364',
  pink: '#D85B8E',
  purple: '#8167C9',
  indigo: '#526FD1',
  blue: '#3B82C4',
  milk: '#8DA9BF',
  oat: '#B89B6A',
  coffee: '#8A5C4A',
  coffeeDark: '#68483F',
  tea: '#9B733F',
  wine: '#9D3D55',
  neutral: '#8B8D92',
} as const;

function builtin(
  id: string,
  name: string,
  hydrationPercent: number,
  standardVolumeMl: number,
  color: string,
  icon: Drink['icon'],
): Drink {
  return {
    id: `builtin-${id}`,
    name,
    hydrationPercent,
    standardVolumeMl,
    color,
    icon,
    isBuiltin: true,
    createdAt: CATALOG_V4_TIMESTAMP,
    updatedAt: CATALOG_V4_TIMESTAMP,
  };
}

/**
 * Каталог V4 перенесён по предоставленным пользователем референсам. Значения
 * гидратации намеренно являются продуктовыми коэффициентами, в том числе могут
 * быть отрицательными для алкоголя.
 */
export const BUILTIN_DRINKS: readonly Drink[] = [
  builtin('water', 'Вода', 100, 250, palette.water, 'water'),
  builtin('green-tea', 'Зелёный чай', 90, 250, palette.green, 'tea'),
  builtin('coffee', 'Кофе', 60, 200, palette.coffee, 'coffee'),
  builtin('juice', 'Сок', 95, 200, palette.orange, 'juice'),
  builtin('soda', 'Газировка', 80, 330, palette.ruby, 'soda'),
  builtin('ayran', 'Айран', 80, 250, palette.milk, 'milk'),
  builtin('amazake', 'Амадзакэ', 80, 200, palette.amber, 'kvass'),
  builtin('americano', 'Американо', 70, 250, palette.coffeeDark, 'coffee'),
  builtin('arnold-palmer', 'Арнольд Палмер', 90, 350, palette.orange, 'juice'),
  builtin('bubble-tea', 'Бабл-ти', 85, 400, palette.purple, 'tea'),
  builtin('baijiu', 'Байцзю', -318, 50, palette.oat, 'cocktail'),
  builtin(
    'non-alcoholic-bloody-mary',
    'Безалкогольная Кровавая Мэри',
    90,
    300,
    palette.red,
    'cocktail',
  ),
  builtin(
    'non-alcoholic-margarita',
    'Безалкогольная Маргарита',
    85,
    250,
    palette.yellow,
    'cocktail',
  ),
  builtin(
    'non-alcoholic-pina-colada',
    'Безалкогольная Пина Колада',
    85,
    300,
    palette.amber,
    'cocktail',
  ),
  builtin(
    'non-alcoholic-mojito',
    'Безалкогольный Мохито',
    90,
    300,
    palette.lime,
    'cocktail',
  ),
  builtin('white-wine', 'Белое вино', -95, 150, palette.yellow, 'wine'),
  builtin('white-tea', 'Белый чай', 95, 250, palette.yellow, 'tea'),
  builtin(
    'caffeine-free-diet-soda',
    'Бескофеиновая диетическая сода',
    85,
    330,
    palette.amber,
    'soda',
  ),
  builtin('decaf-tea', 'Бескофеиновый чай', 95, 250, palette.yellow, 'tea'),
  builtin('gimlet', 'Буравчик', -25, 150, palette.lime, 'cocktail'),
  builtin('vermouth', 'Вермут', -95, 100, palette.teal, 'wine'),
  builtin('non-alcoholic-wine', 'Вино б/а', 70, 150, palette.coral, 'wine'),
  builtin('whisky', 'Виски', -318, 50, palette.orange, 'cocktail'),
  builtin('whisky-sour', 'Виски сауэр', -25, 150, palette.amber, 'cocktail'),
  builtin('vodka', 'Водка', -318, 50, palette.milk, 'wine'),
  builtin('mulled-wine', 'Глинтвейн', -95, 200, palette.ruby, 'wine'),
  builtin('daiquiri', 'Дайкири', -20, 150, palette.lime, 'cocktail'),
  builtin('gin', 'Джин', -318, 50, palette.teal, 'cocktail'),
  builtin('gin-tonic', 'Джин-тоник', -20, 300, palette.lime, 'cocktail'),
  builtin(
    'diet-soda',
    'Диетическая газировка',
    83,
    330,
    palette.purple,
    'soda',
  ),
  builtin('ginger-beer', 'Имбирное пиво', 85, 330, palette.amber, 'beer'),
  builtin('ginger-ale', 'Имбирный эль', 85, 330, palette.yellow, 'soda'),
  builtin('yogurt', 'Йогурт', 70, 250, palette.pink, 'milk'),
  builtin('cocoa', 'Какао', 80, 250, palette.coffee, 'coffee'),
  builtin('cappuccino', 'Капучино', 60, 200, palette.coffee, 'coffee'),
  builtin(
    'plant-cappuccino',
    'Капучино на растительной основе',
    60,
    200,
    palette.oat,
    'coffee',
  ),
  builtin('kefir', 'Кефир', 70, 250, palette.milk, 'milk'),
  builtin('coconut-water', 'Кокосовая вода', 90, 250, palette.purple, 'water'),
  builtin('cold-brew', 'Колд-брю', 80, 300, palette.coffee, 'coffee'),
  builtin('kombucha', 'Комбуча', 70, 250, palette.amber, 'tea'),
  builtin('cognac', 'Коньяк', -318, 50, palette.orange, 'wine'),
  builtin('root-beer', 'Корневое пиво', 80, 330, palette.wine, 'beer'),
  builtin(
    'royal-milk-tea',
    'Королевский молочный чай',
    85,
    300,
    palette.amber,
    'tea',
  ),
  builtin('cosmopolitan', 'Космополитен', -25, 150, palette.red, 'cocktail'),
  builtin('bone-broth', 'Костный бульон', 75, 250, palette.amber, 'broth'),
  builtin(
    'decaf-coffee',
    'Кофе без кофеина',
    90,
    200,
    palette.coffee,
    'coffee',
  ),
  builtin('red-wine', 'Красное вино', -95, 150, palette.wine, 'wine'),
  builtin('spirits', 'Крепкий алкоголь', -318, 50, palette.orange, 'cocktail'),
  builtin('bloody-mary', 'Кровавая Мэри', -20, 300, palette.red, 'cocktail'),
  builtin(
    'bloody-caesar',
    'Кровавый Цезарь',
    -20,
    300,
    palette.red,
    'cocktail',
  ),
  builtin('latte', 'Латте', 60, 300, palette.coffee, 'coffee'),
  builtin(
    'plant-latte',
    'Латте на растительной основе',
    60,
    300,
    palette.amber,
    'coffee',
  ),
  builtin('lemonade', 'Лимонад', 90, 300, palette.yellow, 'soda'),
  builtin('long-drink', 'Лонг', -23, 300, palette.green, 'cocktail'),
  builtin('long-island', 'Лонг-Айленд', -20, 300, palette.yellow, 'cocktail'),
  builtin('mai-tai', 'Май Тай', -20, 250, palette.amber, 'cocktail'),
  builtin('macchiato', 'Макиато', 45, 100, palette.coffeeDark, 'coffee'),
  builtin('makgeolli', 'Макколли', -70, 200, palette.yellow, 'wine'),
  builtin('manhattan', 'Манхэттен', -20, 150, palette.coral, 'cocktail'),
  builtin('margarita', 'Маргарита', -26, 200, palette.yellow, 'cocktail'),
  builtin('matcha', 'Матча', 90, 250, palette.green, 'tea'),
  builtin('mimosa', 'Мимоза', -23, 200, palette.yellow, 'cocktail'),
  builtin('almond-milk', 'Миндальное молоко', 90, 250, palette.oat, 'milk'),
  builtin(
    'mineral-water',
    'Минеральная вода',
    100,
    250,
    palette.water,
    'water',
  ),
  builtin('mochaccino', 'Моккачино', 55, 300, palette.coffee, 'coffee'),
  builtin('milk', 'Молоко', 130, 250, palette.milk, 'milk'),
  builtin('milkshake', 'Молочный коктейль', 80, 350, palette.pink, 'milk'),
  builtin('mojito', 'Мохито', -20, 300, palette.lime, 'cocktail'),
  builtin('aloe-drink', 'Напиток с алоэ вера', 85, 300, palette.teal, 'juice'),
  builtin(
    'grass-jelly-drink',
    'Напиток с травяным желе',
    85,
    300,
    palette.wine,
    'tea',
  ),
  builtin('negroni', 'Негрони', -30, 150, palette.coral, 'cocktail'),
  builtin('skim-milk', 'Обезжиренное молоко', 91, 250, palette.purple, 'milk'),
  builtin('oat-milk', 'Овсяное молоко', 89, 250, palette.indigo, 'milk'),
  builtin('old-fashioned', 'Олд фешен', -30, 150, palette.orange, 'cocktail'),
  builtin('beer', 'Пиво', -40, 500, palette.yellow, 'beer'),
  builtin('non-alcoholic-beer', 'Пиво б/а', 70, 500, palette.yellow, 'beer'),
  builtin('pina-colada', 'Пина Колада', -23, 300, palette.amber, 'cocktail'),
  builtin('protein-shake', 'Протеин', 80, 350, palette.blue, 'sports'),
  builtin('pu-erh', 'Пуэр', 85, 250, palette.tea, 'tea'),
  builtin('radler', 'Радлер', -40, 500, palette.yellow, 'beer'),
  builtin(
    'rye-and-ginger',
    'Рай энд джинджер',
    -20,
    300,
    palette.amber,
    'cocktail',
  ),
  builtin('raki', 'Ракы', -200, 50, palette.neutral, 'wine'),
  builtin('roy-rogers', 'Рой Роджерс', 90, 300, palette.ruby, 'cocktail'),
  builtin('rum', 'Ром', -318, 50, palette.orange, 'cocktail'),
  builtin('sake', 'Саке', -95, 100, palette.lime, 'wine'),
  builtin('sangria', 'Сангрия', -70, 250, palette.ruby, 'wine'),
  builtin(
    'sex-on-the-beach',
    'Секс на пляже',
    -20,
    300,
    palette.coral,
    'cocktail',
  ),
  builtin('cider', 'Сидр', -40, 500, palette.ruby, 'beer'),
  builtin('sikhye', 'Сикхе', 90, 250, palette.amber, 'kvass'),
  builtin('smoothie', 'Смузи', 70, 350, palette.pink, 'juice'),
  builtin('soju', 'Соджу', -100, 50, palette.lime, 'wine'),
  builtin('soy-milk', 'Соевое молоко', 90, 250, palette.milk, 'milk'),
  builtin(
    'sports-drink',
    'Спортивный напиток',
    96,
    500,
    palette.purple,
    'sports',
  ),
  builtin('suanmeitang', 'Суанмэйтан', 90, 300, palette.wine, 'juice'),
  builtin('soup', 'Суп', 60, 300, palette.oat, 'broth'),
  builtin('tequila', 'Текила', -318, 50, palette.amber, 'wine'),
  builtin('champagne', 'Шампанское', -95, 150, palette.yellow, 'wine'),
  builtin('shirley-temple', 'Ширли Темпл', 80, 300, palette.pink, 'cocktail'),
  builtin('schnapps', 'Шнапс', -200, 50, palette.ruby, 'wine'),
  builtin('shot', 'Шот', -159, 50, palette.purple, 'cocktail'),
  builtin('energy-drink', 'Энергетик', 55, 250, palette.indigo, 'energy'),
  builtin('espresso', 'Эспрессо', 40, 60, palette.coffeeDark, 'coffee'),
  builtin(
    'espresso-martini',
    'Эспрессо мартини',
    -90,
    150,
    palette.coffeeDark,
    'cocktail',
  ),
  builtin(
    'apple-spritzer',
    'Яблочный шпритцер',
    90,
    300,
    palette.amber,
    'juice',
  ),
  builtin('barley-tea', 'Ячменный чай', 95, 250, palette.amber, 'tea'),
  builtin('herbal-tea', 'Травяной чай', 90, 250, palette.lime, 'tea'),
  builtin('flat-white', 'Флэт уайт', 70, 200, palette.coffee, 'coffee'),
  builtin('fruit-tea', 'Фруктовый чай', 90, 250, palette.coral, 'tea'),
  builtin('hard-seltzer', 'Хард-зельцер', -40, 330, palette.lime, 'soda'),
  builtin('iced-tea', 'Холодный чай', 90, 330, palette.tea, 'tea'),
  builtin(
    'chrysanthemum-tea',
    'Хризантемовый чай',
    95,
    250,
    palette.yellow,
    'tea',
  ),
  builtin('hugo', 'Хуго', -20, 300, palette.lime, 'cocktail'),
  builtin('chicory', 'Цикорий', 85, 250, palette.wine, 'coffee'),
  builtin('tea-latte', 'Чай латте', 100, 300, palette.amber, 'tea'),
  builtin('oolong-tea', 'Чай улун', 90, 250, palette.orange, 'tea'),
  builtin('black-tea', 'Чёрный чай', 90, 250, palette.tea, 'tea'),
];

/** Идентификаторы каталога, который уже мог быть изменён или скрыт пользователем. */
export const PREVIOUS_BUILTIN_IDS_V3 = new Set([
  'builtin-water',
  'builtin-tea',
  'builtin-coffee',
  'builtin-milk',
  'builtin-juice',
  'builtin-soda',
  'builtin-sparkling-water',
  'builtin-mineral-water',
  'builtin-electrolyte-water',
  'builtin-coconut-water',
  'builtin-sports-drink',
  'builtin-black-tea',
  'builtin-green-tea',
  'builtin-herbal-tea',
  'builtin-iced-tea',
  'builtin-matcha',
  'builtin-black-coffee',
  'builtin-espresso',
  'builtin-decaf-coffee',
  'builtin-latte',
  'builtin-cappuccino',
  'builtin-whole-milk',
  'builtin-skim-milk',
  'builtin-plant-milk',
  'builtin-chocolate-milk',
  'builtin-kefir',
  'builtin-ayran',
  'builtin-orange-juice',
  'builtin-apple-juice',
  'builtin-tomato-juice',
  'builtin-smoothie',
  'builtin-fruit-drink',
  'builtin-compote',
  'builtin-diet-soda',
  'builtin-energy-drink',
  'builtin-lemonade',
  'builtin-kombucha',
  'builtin-kvass',
  'builtin-broth',
  'builtin-cocoa',
  'builtin-hot-chocolate',
  'builtin-protein-shake',
  'builtin-milkshake',
  'builtin-non-alcoholic-beer',
  'builtin-beer',
  'builtin-wine',
  'builtin-spirits',
]);

export const PREVIOUS_BUILTIN_TIMESTAMPS = new Set([
  '2026-07-11T00:00:00.000Z',
  '2026-07-14T00:00:00.000Z',
]);

function legacyV2(
  id: string,
  name: string,
  hydrationPercent: number,
  standardVolumeMl: number,
  color: string,
  icon: Drink['icon'],
): Drink {
  return {
    id: `builtin-${id}`,
    name,
    hydrationPercent,
    standardVolumeMl,
    color,
    icon,
    isBuiltin: true,
    createdAt: '2026-07-14T00:00:00.000Z',
    updatedAt: '2026-07-14T00:00:00.000Z',
  };
}

// Старый набор нужен только для последовательной миграции баз версии 1 → 2 → 4.
export const NEW_BUILTIN_DRINKS_V2: readonly Drink[] = [
  legacyV2(
    'sparkling-water',
    'Газированная вода',
    100,
    250,
    '#62C9D8',
    'sparkling',
  ),
  legacyV2('mineral-water', 'Минеральная вода', 100, 250, '#55B8CF', 'water'),
  legacyV2(
    'electrolyte-water',
    'Вода с электролитами',
    100,
    500,
    '#35B9A9',
    'water',
  ),
  legacyV2('coconut-water', 'Кокосовая вода', 95, 250, '#B6C76A', 'juice'),
  legacyV2('sports-drink', 'Спортивный напиток', 95, 500, '#5FC6A8', 'sports'),
  legacyV2('black-tea', 'Чёрный чай', 95, 250, '#B58A55', 'tea'),
  legacyV2('green-tea', 'Зелёный чай', 95, 250, '#8EBE63', 'tea'),
  legacyV2('herbal-tea', 'Травяной чай', 98, 250, '#70B77E', 'tea'),
  legacyV2('iced-tea', 'Холодный чай', 90, 330, '#C39B55', 'tea'),
  legacyV2('matcha', 'Матча', 90, 250, '#80AD55', 'tea'),
  legacyV2('black-coffee', 'Чёрный кофе', 90, 200, '#76513E', 'coffee'),
  legacyV2('espresso', 'Эспрессо', 90, 60, '#684536', 'coffee'),
  legacyV2('decaf-coffee', 'Кофе без кофеина', 95, 200, '#92705A', 'coffee'),
  legacyV2('latte', 'Латте', 90, 300, '#B8906E', 'coffee'),
  legacyV2('cappuccino', 'Капучино', 90, 200, '#A77A5A', 'coffee'),
  legacyV2('whole-milk', 'Цельное молоко', 95, 250, '#AFC9D3', 'milk'),
  legacyV2('skim-milk', 'Обезжиренное молоко', 95, 250, '#C0D8DF', 'milk'),
  legacyV2('plant-milk', 'Растительное молоко', 90, 250, '#D2C39D', 'milk'),
  legacyV2('chocolate-milk', 'Шоколадное молоко', 90, 250, '#A9785D', 'milk'),
  legacyV2('kefir', 'Кефир', 90, 250, '#BFD6D8', 'milk'),
  legacyV2('ayran', 'Айран', 95, 250, '#B4D4DA', 'milk'),
  legacyV2('orange-juice', 'Апельсиновый сок', 90, 200, '#F29A4A', 'juice'),
  legacyV2('apple-juice', 'Яблочный сок', 88, 200, '#E0B74F', 'juice'),
  legacyV2('tomato-juice', 'Томатный сок', 94, 200, '#D9684C', 'juice'),
  legacyV2('smoothie', 'Смузи', 80, 300, '#D46F91', 'cocktail'),
  legacyV2('fruit-drink', 'Морс', 90, 250, '#C85A78', 'juice'),
  legacyV2('compote', 'Компот', 90, 250, '#C97B67', 'juice'),
  legacyV2('diet-soda', 'Газировка без сахара', 95, 330, '#8F9BE8', 'soda'),
  legacyV2(
    'energy-drink',
    'Энергетический напиток',
    85,
    250,
    '#DCB645',
    'energy',
  ),
  legacyV2('lemonade', 'Лимонад', 90, 300, '#E2C54F', 'soda'),
  legacyV2('kombucha', 'Комбуча', 90, 250, '#C58A54', 'tea'),
  legacyV2('kvass', 'Квас', 85, 330, '#9B6E4B', 'kvass'),
  legacyV2('broth', 'Бульон', 95, 250, '#D2A85D', 'broth'),
  legacyV2('cocoa', 'Какао', 85, 250, '#9A684F', 'coffee'),
  legacyV2('hot-chocolate', 'Горячий шоколад', 85, 250, '#895541', 'coffee'),
  legacyV2(
    'protein-shake',
    'Протеиновый коктейль',
    85,
    350,
    '#A98CB7',
    'sports',
  ),
  legacyV2('milkshake', 'Молочный коктейль', 80, 350, '#D79DB5', 'cocktail'),
  legacyV2(
    'non-alcoholic-beer',
    'Безалкогольное пиво',
    90,
    500,
    '#D8AA4A',
    'beer',
  ),
  legacyV2('beer', 'Пиво', 80, 500, '#C69135', 'beer'),
  legacyV2('wine', 'Вино', 70, 150, '#A34E67', 'wine'),
  legacyV2('spirits', 'Крепкий алкоголь', 0, 50, '#9A9FA8', 'cocktail'),
];
