import type { Drink } from './models';

const BUILTIN_TIMESTAMP = '2026-07-11T00:00:00.000Z';

export const BUILTIN_DRINKS: readonly Drink[] = [
  {
    id: 'builtin-water',
    name: 'Вода',
    hydrationPercent: 100,
    standardVolumeMl: 250,
    color: '#39BFC0',
    icon: 'water',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
  {
    id: 'builtin-tea',
    name: 'Чай',
    hydrationPercent: 95,
    standardVolumeMl: 250,
    color: '#D7A34B',
    icon: 'tea',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
  {
    id: 'builtin-coffee',
    name: 'Кофе',
    hydrationPercent: 80,
    standardVolumeMl: 200,
    color: '#8B6045',
    icon: 'coffee',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
  {
    id: 'builtin-milk',
    name: 'Молоко',
    hydrationPercent: 90,
    standardVolumeMl: 250,
    color: '#AFC9D3',
    icon: 'milk',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
  {
    id: 'builtin-juice',
    name: 'Сок',
    hydrationPercent: 85,
    standardVolumeMl: 200,
    color: '#F29A4A',
    icon: 'juice',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
  {
    id: 'builtin-soda',
    name: 'Газировка',
    hydrationPercent: 80,
    standardVolumeMl: 330,
    color: '#8C7AE6',
    icon: 'soda',
    isBuiltin: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
  },
];
